### ISSUE TITLE
POST /api/service_templates waits for task, indefinitely

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-api#620] opened 2019-07-02 11:01 UTC
From gitter discussion :point_up: [June 19, 2019 10:15 AM](https://gitter.im/ManageIQ/api?at=5d0a0b30fbcc305cc4a81f66)

reproducer..

```
API.post('/api/service_templates', {"action":"create","resource":{"name":"ff","description":"fff","long_description":"","display":false,"service_template_catalog_id":"","zone_id":"2","prov_type":"generic_ansible_playbook","type":"ServiceTemplateAnsiblePlaybook","additional_tenant_ids":[],"config_info":{"provision":{"repository_id":"23","playbook_id":"304","credential_id":"10","hosts":"localhost","verbosity":"0","log_output":"on_error","extra_vars":{},"execution_ttl":"","become_enabled":false,"dialog_id":"3"},"retirement":{"remove_resources":"yes_without_playbook","verbosity":"0","log_output":"on_error"}}}})
```

This creates a task and waits for it, possibly indefinitely...

```
[----] I, [2019-07-02T10:18:51.022098 #2463:2ad2c140b9c4]  INFO -- : Started POST "/api/service_templates" for ::1 at 2019-07-02 10:18:5
1 +0000
[----] I, [2019-07-02T10:18:51.080605 #2463:2ad2c140b9c4]  INFO -- : Processing by Api::ServiceTemplatesController#create as JSON
...
[----] D, [2019-07-02T10:18:51.311407 #2463:2ad2c140b9c4] DEBUG -- :   ESC[1mESC[35mSQL (2.4ms)ESC[0m  ESC[1mESC[32mINSERT INTO "miq_queue" ("priority", "method_name", "state", "created_on", "updated_on", "queue_name", "class_name", "args", "miq_callback", "zone", "role", "msg_timeout", "miq_task_id", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id"ESC[0m  [["priority", 20], ["method_name", "create_in_provider"], ["state", "ready"], ["created_on", "2019-07-02 10:18:51.302571"], ["updated_on", "2019-07-02 10:18:51.302571"], ["queue_name", "generic"], ["class_name", "ManageIQ::Providers::EmbeddedAnsible::AutomationManager::ConfigurationScript"], ["args", "---\n- 2\n- :name: miq_ddd_provision\n  :description: ''\n  :project: '21'\n  :playbook: Demo/create_user.yml\n  :inventory: 2\n  :become_enabled: false\n  :verbosity: '0'\n  :ask_variables_on_launch: true\n  :ask_limit_on_launch: true\n  :ask_inventory_on_launch: true\n  :ask_credential_on_launch: true\n  :extra_vars: \"{}\"\n  :credential: 2\n"], ["miq_callback", "---\n:class_name: MiqTask\n:instance_id: 366203\n:method_name: :queue_callback\n:args:\n- Finished\n"], ["zone", "default"], ["role", "embedded_ansible"], ["msg_timeout", 600], ["miq_task_id", 366203], ["lock_version", 0]]
...
(repeats once per second:)
[----] D, [2019-07-02T10:18:52.321075 #2463:2ad2c140b9c4] DEBUG -- :   MiqTask Inst Including Associations (0.1ms - 1rows)
[----] D, [2019-07-02T10:18:53.323842 #2463:2ad2c140b9c4] DEBUG -- :   ESC[1mESC[36mMiqTask Load (0.9ms)ESC[0m  ESC[1mESC[34mSELECT  "miq_tasks".* FROM "miq_tasks" WHERE "miq_tasks"."id" = $1 LIMIT $2ESC[0m  [["id", 366203], ["LIMIT", 1]]
...
^C
[----] I, [2019-07-02T10:55:32.210807 #2463:2ad2c140b9c4]  INFO -- : Completed   in 2201130ms (ActiveRecord: 1558.2ms)
```

(Obviously the long wait is because I had no `simulate_queue_worker` running.. but it stays trying to work even when the browser gives up.)

**Comment by himdel** [comment] 2019-07-04 10:53
:rofl: on my other machine...

```
[----] I, [2019-07-04T10:52:11.337348 #22706:2aab912e6aa0]  INFO -- : Completed   in 242851496ms (ActiveRecord: 65039.2ms)
```

**Comment by himdel** [comment] 2020-01-06 12:43
@miq-bot assign abelotti
@miq-bot remove_label stale

**Comment by himdel** [comment] 2020-01-06 12:51
@miq-bot assign lpichler

(I just need somebody from the API team to at least take a look, since nobody has looked in the last 6 months :))

**Comment by Fryguy** [comment] 2020-07-06 18:58
@abellotti Can you verify?

**Comment by abellotti** [comment] 2020-07-07 14:29
I cannot reproduce this.  I just tried that POST /api/service_templates example in the description on master running from source (and no simulate_queue_worker running), and the service template was created and returned the new service template with no wait.

```
[----] I, [2020-07-07T10:26:57.609421 #36922:3fc54fd92534]  INFO -- : Started POST "/api/service_templates" for ::1 at 2020-07-07 10:26:57 -0400

...

[----] I, [2020-07-07T10:26:58.015124 #36922:3fc54fd92534]  INFO -- : Completed 200 OK in 329ms (Views: 0.1ms | ActiveRecord: 42.3ms)
```

**Comment by Fryguy** [comment] 2020-07-13 19:26
@abellotti It sounds like the code is _not_ waiting for the task?  If so, can you close?

**Comment by abellotti** [comment] 2020-07-13 19:37
code does not wait correct, closing.

**Closed by abellotti** 2020-07-13 19:37 UTC
Labels: bug
